-- Roles become a fact about a person *on a project*, not about a person.
--
-- `user_project_roles` had no project dimension at all, so "developer" was something you were
-- everywhere or nowhere: somebody who ships code on one project and runs delivery on another could
-- not be described, and the onboarding track derived from their role had to pick one or give up.
-- `user_project_assignment_roles` has existed since V4 for exactly this, and had **no writer** --
-- it was empty in every deployment since it was created, which is why the admin project user list
-- reported every member as holding no role at all.
--
-- Roles now hang off `ProjectUserAssignment`, and that is the only place they live.
-- `User.projectRoles` survives as a *derived* union across somebody's assignments, for the surfaces
-- whose question really is global (a user list, a profile, the search filter).
--
-- No backfill. This workspace runs dev-only and the database is wiped entirely on each schema
-- change, so there is never a populated `user_project_roles` to carry across -- and there is no
-- Flyway here either: these files are a record of what changed and why, not an operational step.
-- Writing data-movement SQL for a table that is empty by construction would be a migration that
-- looks like it does something and cannot.
DROP TABLE IF EXISTS user_project_roles;
